### ISSUE TITLE
Find out why the user recieves 3 pop-up windows when losing the round

### ISSUE THREAD

**Issue by seledun** [JakobEdvardsson/poker-game#38]
The players receives 3 popup-windows when losing a round

Saying:
1. User won the round 
2. User won the round
3. User lost the round

We need to find out why this behavior is happening.

**Comment by Dautabossy** [comment]
Sa till tabnine om feedback på koden och efter ändring i koden verkar det som att enbart en ruta dyker upp, men något i koden går i sönder:


Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.pokergame.gui.GameController.lambda$updatePots$13(GameController.java:1209)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._enterNestedEventLoopImpl(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._enterNestedEventLoop(WinApplication.java:211)
	at javafx.graphics/com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:515)
	at javafx.graphics/com.sun.glass.ui.EventLoop.enter(EventLoop.java:107)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:647)
	at javafx.graphics/javafx.stage.Stage.showAndWait(Stage.java:469)
	at org.pokergame.gui.WinnerBox.displayWinner(WinnerBox.java:89)
	at org.pokergame.gui.GameController.lambda$setWinnerLabel$11(GameController.java:1142)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by Dautabossy** [comment]
Nej två rutor dyker upp

![Image](https://github.com/JakobEdvardsson/poker-game/assets/114819894/913d5187-ee55-48a2-b973-febefd371249)

**Comment by Dautabossy** [comment]
Denna metoden skapar vinnar rutan, koden ser märklig ut då det finns fler fall att vinna med än vad som ligger kodat?

  public void setWinnerLabel(String winner, int hand) {
    switch (hand) {
      case 0 -> winnerHand = "högsta kort";
      case 1 -> winnerHand = "ett par";
      case 3 -> winnerHand = "två par";
      case 4 -> winnerHand = "triss";
      case 5 -> winnerHand = "straight";
      case 6 -> winnerHand = "flush";
      case 7 -> winnerHand = "full house";
      case 8 -> winnerHand = "four of a kind";
      case 9 -> winnerHand = "straight flush";
      case 99 -> winnerHand = "Du vann när resten av spelarna foldade!";
      case 98 -> winnerHand = "när resterande spelare foldade.";
      case 97 -> winnerHand = "Du förlorade!";
    }

    Platform.runLater(() -> {
      winnerBox = new WinnerBox();

      if(hand < 10){ //Should maybe be if(hand <= 10)
        if(winner.equals(getUsername())){
          sound.playSound("coinSound");
          winnerBox.displayWinner("Rundans vinnare", winner, 1, winnerHand);
        } else {
          winnerBox.displayWinner("Rundans vinnare", winner, 2, winnerHand);
        }
      } else { //If hand is > 10
        if(winner.equals(getUsername())){
          sound.playSound("coinSound");
          winnerBox.displayWinner("Rundans vinnare", winner, 3, winnerHand);
        } else {
          winnerBox.displayWinner("Rundans vinnare", winner, 4, winnerHand);
        }
      }
    });
  }

**Comment by Dautabossy** [comment]
Rad 1149 verkar ha något fel?

Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.pokergame.gui.GameController.lambda$updatePots$13(GameController.java:1209)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._enterNestedEventLoopImpl(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._enterNestedEventLoop(WinApplication.java:211)
	at javafx.graphics/com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:515)
	at javafx.graphics/com.sun.glass.ui.EventLoop.enter(EventLoop.java:107)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:647)
	at javafx.graphics/javafx.stage.Stage.showAndWait(Stage.java:469)
	at org.pokergame.gui.WinnerBox.displayWinner(WinnerBox.java:92)
	at org.pokergame.gui.GameController.lambda$setWinnerLabel$11(GameController.java:1149)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:1583)
